services:
  resign-postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}

volumes:
  postgres-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${POSTGRES_DIR}

networks:
  default:
    driver: bridge
